language: node_js

node_js:
  - "8"

branches:
 only:
   - master
   - /^greenkeeper/.*$/

install:
  - npm install

script:
  - npm run doc
  - npm run lint
  - npm run build
  - npm run test:coveralls